### ISSUE TITLE
migrate to lfs for pip mirror

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-debian-packaging#109]
we should migrate to git-lfs for our pip mirror (instead of S3): this means we're using the same object store as we do for other built artifacts, can more easily audit/track/review, and we can reuse our GH permissions instead of needing to set up AWS creds for everyone. Recall that this is a mirror that will be used at package build time only (and for test builds in CI).

this involves:
* enabling git-lfs in this repository
* enabling github pages in order to serve the static HTML 
* migrating our source tarballs/wheels from S3
* updating the URL of our pip mirror

**Comment by conorsch** [comment]
> enabling github pages in order to serve the static HTML

@emkll notes that GitHub Pages do not support serving files via git-lfs: https://github.com/git-lfs/git-lfs/issues/791. Even so, still worth the migration as described above, with a small change that we'd need to serve a static docroot. If we do that via cron (simplest), there'd be a small lag of 15m or so between updates.

**Comment by conorsch** [comment]
First attempt is adding lfs support to the current repo, replacing the gitignore settings for `localwheels/` with lfs settings. That works well enough for now, but may pose an order-of-operations problem during future updates: since the public URL of the wheel archive will only be updated upon merge of new wheels into the master branch, testing builds is quite tricky.

Working on a dev-compatible workflow for use during review of wheel updates. Using a local HTTP server for the localwheels directory seems to work well enough, but documenting that might not be the best option. Will submit a candidate PR with docs updates. If the friction is too great, then we can move the wheels to a separate repo that enables direct pushes from SD maintainers. May the best workflow win.
