### ISSUE TITLE
Builds failing due to missing sha256sum for charset-normalizer

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-debian-packaging#267]
See example build output here:
https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/1256/workflows/0e05f7f2-e4a3-488d-9dff-4e45c2b7492b/jobs/9779

```
Missing sha256sum for package: charset-normalizer==2.0.4
```

Full build results:
https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/1256/workflows/0e05f7f2-e4a3-488d-9dff-4e45c2b7492b

**Comment by creviera** [comment]
the local wheel for charset-normalizer 2.0.4 was added here: https://github.com/freedomofpress/securedrop-debian-packaging/pull/263 and the sha256sum for the proxy and client were added here: https://github.com/freedomofpress/securedrop-proxy/blob/9c1df600eade3984a75c0b090811811b7ef43f9f/requirements/build-requirements.txt#L2 and here: https://github.com/freedomofpress/securedrop-client/blob/20ebedb425e520329b88d38e1f7d57be541e503d/requirements/build-requirements.txt#L4, which should be `cd9a4492eef4e5276c07f9c0dc1338e7be3e95f2a536bf2c5b620b1f27d03d74`

since these are release blockers i'm looking into them now

**Comment by eloquence** [comment]
Thanks for the quick check. The issue was that the "build nightlies" branch was only partially rebased and missing some of those commits (sorry, my bad). This should now be fixed and we're back in business :)
