### ISSUE TITLE
Buster dev build of securedrop-client failing due to compat issue

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-debian-packaging#333]
## Steps to reproduce

On an up-to-date Buster VM, attempt to build a dev package following the [instructions in the README](https://github.com/freedomofpress/securedrop-debian-packaging#build-a-package-for-development-or-test-skip-signature-verfication) fails.

## Expected behavior

Package is built.

## Actual behavior

As of #329, build fails with error:

>  debian/rules build
> make[1]: Entering directory '/home/user/securedrop-debian-packaging/build/debbuild/packaging/securedrop-client'
> dh build --with python-virtualenv
>    dh_update_autotools_config
>    dh_autoreconf
>    dh_auto_configure
> dh_auto_configure: Please use the third-party "pybuild" build system instead of python-distutils
> dh_auto_configure: This feature was removed in compat 12.
> make[1]: *** [debian/rules:4: build] Error 2
> make[1]: Leaving directory '/home/user/securedrop-debian-packaging/build/debbuild/packaging/securedrop-client'
> dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

## Analysis

Lowering the compat level in this file to 11 resolved the issue for me.

**Comment by creviera** [comment]
I can confirm that we are no longer able to build a bullseye or buster package by pointing our builder at a source tarball via:
`PKG_PATH=path/to/source/tarball make package-name`.

I can also confirm that switching to compat 11 fixes this issue for both buster and bullseye. 

We could either lower the compat to 11 (making debhelper more backwards compatible) or do what it suggests by using `pybuild` instead of `python-distutils`. @legoktm are you investigating the second option here (using `pybuild`)? If not, or if you think it'll take some time to investigate, we might want to switch to compat 11 so that we can fix this in the meantime. It looks like 13.7.1 is the latest version of dh, so not sure how version 12 was selected- do you know why? 

(For more info: https://manpages.debian.org/testing/debhelper/debhelper.7.en.html#COMPATIBILITY_LEVELS)
