### ISSUE TITLE
`securedrop-workstation-viewer` nightly jobs should follow Debian version

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-debian-packaging#362]
After #342, the `build-nightly-${VERSION_CODENAME}-securedrop-workstation-viewer` jobs must follow e5640b8f5316e7f537d8e9f1429f1b176bb6f687 in using `{set,get}metapackageversionplatform` and `updatedebianchangelogplatform` so that the version and changelog will be updated for the correct Debian version.  Otherwise `{set,get}metapackageversion` and `updatedebianchangelog` will make the build a no-op and `git commit` will fail, as we see now in (e.g.) <https://app.circleci.com/pipelines/github/freedomofpress/securedrop-debian-packaging/1788/workflows/e9a77269-fd6e-4764-9538-af175da1b605/jobs/15205>.

**Comment by cfm** [comment]
@legoktm, looking at e5640b8f5316e7f537d8e9f1429f1b176bb6f687, is there any reason we shouldn't go ahead and replace the following steps entirely?

| Hard-coded for `buster` | → | Parameterized on `$VERSION_CODENAME` |
| --- | --- | --- |
| `setnightlymetapackageversion` | → | `setnightlymetapackageversionplatform` |
| `getnightlymetapackageversion` | → | `getnightlymetapackageversionplatform` |
| `updatedebianchangelog` | → | `updatedebianpackagechangelogversion` |

**Comment by legoktm** [comment]
Hmm, I didn't realize that other people had introduced `changelog-bullseye` files, that wasn't the intention. It should only be used where the buster and bullseye changelogs needed to diverge (like for the kernel grsec packages). Otherwise all the other packages were supposed to use `changelog-buster`, and once the release pressure was all over (so like now), we'd bulk rename them all to plain `changelog` and stop worrying about varying it by distro.

**Comment by cfm** [comment]
I've opened #365 with the concrete fix for the job that's currently failing, unless there are objections to this compromise.  :-)

**Comment by legoktm** [comment]
> @legoktm - correct me if I'm wrong but I believe there are breaking changes between the buster and bullseye versions

There are, but that's mostly besides the point. When you see `changelog-buster` you really should read it as just `changelog`. The only reason I didn't rename it to drop the platform suffix is because it would've required coordination across multiple repos and it was easier just to keep it the same and have the build script to do the renaming. My goal is that once we move the debian/ folders to the individual component repositories we will do the rename then, since it already requires coordination across those multiple repos.

The exception of course is the kernel, which needs different changelogs for buster and bullseye because of the magic we're doing with version numbers.

So I think the solution should be to delete the changelog-bullseye files (with the exception of the grsec one), merging the changelog entry to be on top of the changelog-buster one. Does that sound like a good way forward @cfm?

**Comment by cfm** [comment]
See #366 for this (much simpler!) approach, all `chore` and no `ci`.  :-)
