### ISSUE TITLE
Makefile target fetch-wheels changes the timestamp of the wheels

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-debian-packaging#46]
The `fetch-wheels` makefile target changes the timestamp of the wheel files. This means when I try to resync the localwheels directory to the S3 bucket, it sync all the files again.

We should modify the script so that it can keep the original timestamp of the files.

@conorsch

**Comment by conorsch** [comment]
The lack of reliable timestamps during fetch is a side-effect of using object storage buckets for the wheels, rather than, say, rsync via ssh. Fetching over HTTPS simply doesn't afford an opportunity to compare timestamps.

One option may be to pass `--exact-timestamps` when pulling _from_ S3, rather than fetching via curl or wget. See `aws s3 sync help` for more info. We'll still need to trust checksums and signatures in order to verify integrity, rather than skipping based on timestamp, given that the `--exact-timestamps` flag appears to be relevant only for pulls from, rather than pushes to, S3.

See also the `--size-only` option to s3 sync, which would skip uploads based on filesize. Take it for a spin and comment on what you see as the best approach, @kushaldas.

Before making any changes to the recommended workflow, let's make sure to tackle https://github.com/freedomofpress/securedrop-debian-packaging/issues/55 so we're updating the documentation accordingly.

**Comment by conorsch** [comment]
As of #124, we're no longer using S3 for storing the binary wheel feels. Instead, we use git-lfs, so the files will be present locally—without needing to "fetch" via a separate action—and timestamps will persist from whenever they were pulled in via git. Additional metadata about time of creation via commit is of course available via standard git tooling.
